In [1]:
# Exercise 1: Create and reshape numpy array
import numpy as np

arr = np.arange(1, 11)  # Creates array [1, 2, ..., 10]
reshaped_arr = arr.reshape(2, 5)  # Reshapes to 2x5 matrix
print(reshaped_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [2]:
# Exercise 2: Extract elements from numpy array
import numpy as np

arr = np.arange(1, 21)  # Creates array [1, 2, ..., 20]
extracted_elements = arr[5:15]  # Extracts elements from index 5 to 14
print(extracted_elements)

[ 6  7  8  9 10 11 12 13 14 15]


In [5]:
# Exercise 3: Create and modify Pandas Series
import pandas as pd

fruit_series = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})
fruit_series['pears'] = 4  # Adds new item
print(fruit_series)

apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [6]:
# Exercise 4: Create DataFrame with sample data
import pandas as pd
import numpy as np

data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Henry', 'Ivy', 'Jack'],
    'age': np.random.randint(20, 50, size=10),
    'gender': np.random.choice(['Male', 'Female'], size=10)
}

df = pd.DataFrame(data)
print(df)

      name  age  gender
0    Alice   44  Female
1      Bob   21  Female
2  Charlie   47    Male
3    David   39    Male
4      Eve   38    Male
5    Frank   20    Male
6    Grace   35  Female
7    Henry   26  Female
8      Ivy   20  Female
9     Jack   49  Female


In [7]:
# Exercise 5: Add occupation column

# Continuing from Exercise 4
occupations = ['Programmer', 'Manager', 'Analyst'] * 3 + ['Programmer']
df['occupation'] = occupations[:10] 
print(df)

      name  age  gender  occupation
0    Alice   44  Female  Programmer
1      Bob   21  Female     Manager
2  Charlie   47    Male     Analyst
3    David   39    Male  Programmer
4      Eve   38    Male     Manager
5    Frank   20    Male     Analyst
6    Grace   35  Female  Programmer
7    Henry   26  Female     Manager
8      Ivy   20  Female     Analyst
9     Jack   49  Female  Programmer


In [8]:
# Exercise 6: Filter rows by age
# Continuing from previous exercises
filtered_df = df[df['age'] >= 30]
print(filtered_df)

      name  age  gender  occupation
0    Alice   44  Female  Programmer
2  Charlie   47    Male     Analyst
3    David   39    Male  Programmer
4      Eve   38    Male     Manager
6    Grace   35  Female  Programmer
9     Jack   49  Female  Programmer


In [ ]:
# Exercise 7: Convert to CSV and read back